Updater:
  update_inter: 120
  verbosity: INFO
  percent_resolution: 10000  

Node:
  mnemonic: # your mnemonic here
  oracle_curr: e2ee3c439d71d22a77ccf019953459368b4d35e6184c115d67e1c735
  oracle_addr: addr1wxhsunv3398mrx39wm843pyjd3p4npdp6wftcq9tt8jxvhqh5dja0
  c3_token_hash: 8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a
  c3_token_name: CHARLI3
  reference_script_input: 97c0a07f9d2b732a26bcbc664c99a00120cf5382918972ab0d754fb910799e90#0

ChainQuery:
  network: MAINNET
  blockfrost:
    base_url: https://cardano-mainnet.blockfrost.io/api
    project_id: # your blockfrost project id
  ogmios:
    ws_url: # your ogmios websocket url

Rate:
  base_currency:
    inverseRate:
      type: inverserate
      symbol: ADA/CHARLI3
      quote_currency: True
      rate_calculation_method: "divide"
  quote_currency:
    sundaeswap:
      type: sundaeswap
      symbol: charli3
    muesliswap:
      type: muesliswap
      symbol: CHARLI3/ADA
      currency_symbol: 8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a
      token_name: 434841524c4933
    wingriders:
      type: wingriders
      symbol: CHARLI3/ADA
      currency_symbol: 8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a
      token_name: 434841524c4933
    minswap:
      type: minswap
      pool_tokens: ADA-C3
      pool_id: 2cb05a0cec80aa158dcc9faddf9de6a20a2acec78fa4101e3d271df7947fbcc5
      get_second_pool_price: false
    vyfi:
      type: vyfi
      pool_tokens: ADA-CHARLI3
      pool_address: addr1z8qaqzruv8363uv9q8z653c9zae0ms74xfde35aslpncvxg9gczwem2qwpjcgh3dr055wfyznfc209ke40hayakfmavsax6gz6
      minting_a_token_policy: null
      minting_b_token_policy: 8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a