Updater:
  update_inter: 180
  verbosity: INFO
  percent_resolution: 10000  

Node:
  mnemonic: # your mnemonic
  oracle_curr: 696e58d4453c525cb032a325ea8cde6499ff31ffdec05d3ca8dbaea0
  oracle_addr: addr1w9wccku5krmmn67kp58a4fgwvypemm2fpskh5ldppzx3vpcdkck62
  c3_token_hash: 8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a
  c3_token_name: CHARLI3
  # reference_script_input: 7e495557f83ee369a6ab84fd4f749dd841d0c0f37322b2630550cf886a2b01c3#0
  c3_oracle_nft_hash: e2ee3c439d71d22a77ccf019953459368b4d35e6184c115d67e1c735
  c3_oracle_nft_name: OracleFeed
  c3_oracle_rate_address: addr1wxhsunv3398mrx39wm843pyjd3p4npdp6wftcq9tt8jxvhqh5dja0

ChainQuery:
  network: MAINNET
  ogmios:
    ws_url: # your ogmios ws url

Rate:
  base_currency:
    binance_usdt:
      type: binance
      symbol: ADAUSDT
      quote_currency: true
      rate_calculation_method: divide
    xt:
      type: generic
      symbol: ADA-USDT
      api_url: https://sapi.xt.com
      path: /v4/public/ticker?symbol=ada_usdt
      json_path: ["result", 0, "c"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    gate:
      type: generic
      symbol: ADA-USDT
      api_url: https://api.gateio.ws
      path: /api2/1/ticker/ada_usdt
      json_path: ["last"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    crypto:
      type: generic
      symbol: ADA-USDT
      api_url: https://api.crypto.com
      path: /v2/public/get-ticker?instrument_name=ADA_USDT
      json_path: ["result","data",0,"a"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    huobi:
      type: generic
      symbol: ADAUSDT
      api_url: https://api.huobi.pro
      path: /market/trade?symbol=adausdt
      json_path: ["tick","data",0,"price"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    coinbase:
      type: generic
      symbol: ADA-USD
      api_url: https://api.exchange.coinbase.com
      path: /products/ADA-USD/ticker/
      json_path: ["price"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    kraken:
      type: generic
      symbol: ADAUSD
      api_url: https://api.kraken.com
      path: /0/public/Ticker?pair=ADAUSD
      json_path: ["result","ADAUSD","o"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    binance_busd:
      type: binance
      symbol: ADABUSD
      quote_currency: true
      rate_calculation_method: divide
    bitget:
      type: generic
      symbol: ADA-USDC
      api_url: https://api.bitget.com
      path: /api/spot/v1/market/ticker?symbol=ADAUSDC_SPBL
      json_path: ["data","close"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    kucoin:
      type: generic
      symbol: ADA-USDC
      api_url: https://api.kucoin.com
      path: /api/v1/market/orderbook/level1?symbol=ADA-USDC
      json_path: ["data","price"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    okx:
      type: generic
      symbol: ADA-USDC
      api_url: https://www.okx.com
      path: /api/v5/market/ticker?instId=ADA-USDC
      json_path: ["data",0,"last"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
  quote_currency:
    coinmarketcap_dchf:
      type: generic
      symbol: DCHF/USD
      api_url: 'https://pro-api.coinmarketcap.com'
      path: /v1/cryptocurrency/quotes/latest?symbol=DCHF
      json_path: ["data","DCHF","quote","USD","price"]
      key:
        X-CMC_PRO_API_KEY: cc8dd3a2-67f9-4bc6-8378-c0f9823109e0
    coinmarketcap_xchf:
      type: generic
      symbol: XCHF/USD
      api_url: 'https://pro-api.coinmarketcap.com'
      path: /v1/cryptocurrency/quotes/latest?symbol=XCHF
      json_path: ["data","XCHF","quote","USD","price"]
      key:
        X-CMC_PRO_API_KEY: cc8dd3a2-67f9-4bc6-8378-c0f9823109e0
    coingecko_chf:
      type: coingecko
      tid: superfrank
      vs_currency: usd
    coingecko_vchf:
      type: coingecko
      tid: vnx-swiss-franc
      vs_currency: usd
    coingecko_xchf:
      type: coingecko
      tid: cryptofranc
      vs_currency: usd
    coingecko_dchf:
      type: coingecko
      tid: defi-franc
      vs_currency: usd
    coingecko_jchf:
      type: coingecko
      tid: jarvis-synthetic-swiss-franc
      vs_currency: usd