Updater:
  update_inter: 120
  verbosity: INFO
  percent_resolution: 10000  

Node:
  mnemonic: # mnemonic for the oracle node
  oracle_curr: ba0b98665d9a18c04c50793768780dff7826e2bcff2ff0909b708fa0
  oracle_addr: addr1w8ny03yac08cg7fsga6usveag4za2t0whmfzjdqflq3vu5qxarwzw
  c3_token_hash: 8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a
  c3_token_name: CHARLI3
  reference_script_input: 90dcb61413be3e73ebe3828bcf41b9f4616e6c8259ae0141c839bd24833c43fa#0
  c3_oracle_nft_hash: e2ee3c439d71d22a77ccf019953459368b4d35e6184c115d67e1c735
  c3_oracle_nft_name: OracleFeed
  c3_oracle_rate_address: addr1wxhsunv3398mrx39wm843pyjd3p4npdp6wftcq9tt8jxvhqh5dja0

ChainQuery:
  network: MAINNET
  blockfrost:
    base_url: https://cardano-mainnet.blockfrost.io/api
    project_id: # blockfrost project id
  ogmios:
    ws_url: # ogmios websocket url

Rate:
  base_currency:
    vyfi:
      type: vyfi
      pool_tokens: ADA-BOOK
      pool_address: addr1z9tjkpp9kksyuysnjxjjuenfxv0ym0dlus3fxkfu8gmp34mend0q3h5twed567pu236a0sf6vfgruxgpr4rkxryyx0zq6367vh
      minting_a_token_policy: null
      minting_b_token_policy: 51a5e236c4de3af2b8020442e2a26f454fda3b04cb621c1294a0ef34
      get_second_pool_price: false
      quote_currency: true
    sundaeswap:
      type: sundaeswap
      symbol: book
      quote_currency: true
    minswap:
      type: minswap
      pool_tokens: ADA-BOOK
      pool_id: 2ed309a7ecb6d0d5e00dca0bcc3924fdc0627a5fb631f1acc4deb898b14ee8bd
      get_second_pool_price: false
      quote_currency: true
    wingriders:
      type: wingriders
      symbol: BOOK
      currency_symbol: 51a5e236c4de3af2b8020442e2a26f454fda3b04cb621c1294a0ef34
      token_name: 424f4f4b
      quote_currency: true
    coingecko:
      type: coingecko
      tid: book-2
      vs_currency: usd
  quote_currency:
    binance_usdt:
      type: binance
      symbol: ADAUSDT
    xt:
      type: generic
      symbol: ADA-USDT
      api_url: https://sapi.xt.com
      path: /v4/public/ticker?symbol=ada_usdt
      json_path: ["result", 0, "c"]
      key: {}
    gate:
      type: generic
      symbol: ADA-USDT
      api_url: https://api.gateio.ws
      path: /api2/1/ticker/ada_usdt
      json_path: ["last"]
      key: {}
    crypto:
      type: generic
      symbol: ADA-USDT
      api_url: https://api.crypto.com
      path: /v2/public/get-ticker?instrument_name=ADA_USDT
      json_path: ["result","data",0,"a"]
      key: {}
    huobi:
      type: generic
      symbol: ADAUSDT
      api_url: https://api.huobi.pro
      path: /market/trade?symbol=adausdt
      json_path: ["tick","data",0,"price"]
      key: {}
    coinbase:
      type: generic
      symbol: ADA-USD
      api_url: https://api.exchange.coinbase.com
      path: /products/ADA-USD/ticker/
      json_path: ["price"]
      key: {}
    kraken:
      type: generic
      symbol: ADAUSD
      api_url: https://api.kraken.com
      path: /0/public/Ticker?pair=ADAUSD
      json_path: ["result","ADAUSD","o"]
      key: {}
    btse:
      type: generic
      symbol: ADAUSD
      api_url: https://api.btse.com
      path: /spot/api/v3.2/price?symbol=ADA-USD
      json_path: [0,"lastPrice"]
      key: {}
    bitfinex:
      type: generic
      symbol: ADAUSD
      api_url: https://api.bitfinex.com
      path: /v2/ticker/tADAUSD
      json_path: [6]
      key: {}
    binance_busd:
      type: binance
      symbol: ADABUSD
    bitget:
      type: generic
      symbol: ADA-USDC
      api_url: https://api.bitget.com
      path: /api/spot/v1/market/ticker?symbol=ADAUSDC_SPBL
      json_path: ["data","close"]
      key: {}
    kucoin:
      type: generic
      symbol: ADA-USDC
      api_url: https://api.kucoin.com
      path: /api/v1/market/orderbook/level1?symbol=ADA-USDC
      json_path: ["data","price"]
      key: {}
    okx:
      type: generic
      symbol: ADA-USDC
      api_url: https://www.okx.com
      path: /api/v5/market/ticker?instId=ADA-USDC
      json_path: ["data",0,"last"]
      key: {}