include: dynamic_config.yml  

Node:
  mnemonic: <%= @mnemonic_btc_ada %>
  oracle_curr: 2e3ed96d283a549580e29dd6ec23e5f4a8020a8c1d7f2b95c4b2b4dd
  oracle_address: addr1wyujem6fwxju9arc45lm98z0uwgwm0t8aerjp5mgahpgx7snfcpuu
  c3_token_hash: 8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a
  c3_token_name: CHARLI3
  reference_script_input: 0252279ec287e2f0e349bd9d7cddefd7b00569a95d2e508560608e57a430bb1b#0
  c3_oracle_nft_hash: e2ee3c439d71d22a77ccf019953459368b4d35e6184c115d67e1c735
  c3_oracle_nft_name: OracleFeed
  c3_oracle_rate_address: addr1wxhsunv3398mrx39wm843pyjd3p4npdp6wftcq9tt8jxvhqh5dja0

Rate:
  general_base_symbol: BTC-USD
  general_quote_symbol: USD-ADA

  base_currency:
    api_sources:
      - adapter: generic-api
        asset_a: BTC
        asset_b: USDT
        quote_required: true
        quote_calc_method: multiply
        sources:
          - name: xt
            api_url: "https://sapi.xt.com/v4/public/ticker?symbol=BTC_usdt"
            json_path: ["result", 0, "c"]
            headers: {}

          - name: gate
            api_url: "https://api.gateio.ws/api2/1/ticker/BTC_usdt"
            json_path: ["last"]
            headers: {}

          - name: crypto
            api_url: "https://api.crypto.com/v2/public/get-ticker?instrument_name=BTC_USDT"
            json_path: ["result", "data", 0, "a"]
            headers: {}

          - name: huobi
            api_url: "https://api.huobi.pro/market/trade?symbol=btcusdt"
            json_path: ["tick", "data", 0, "price"]
            headers: {}

          - name: coinbase
            api_url: "https://api.exchange.coinbase.com/products/BTC-USD/ticker/"
            json_path: ["price"]
            headers: {}

          - name: kraken
            api_url: "https://api.kraken.com/0/public/Ticker?pair=BTCUSD"
            json_path: ["result", "XXBTZUSD", "o"]
            headers: {}

          - name: btse
            api_url: "https://api.btse.com/spot/api/v3.2/price?symbol=BTC-USD"
            json_path: [0, "lastPrice"]
            headers: {}

          - name: bitfinex
            api_url: "https://api.bitfinex.com/v2/ticker/tBTCUSD"
            json_path: [6]
            headers: {}

          - name: bitrue
            api_url: "https://openapi.bitrue.com/api/v1/ticker/price?symbol=btcusdt"
            json_path: ["price"]
            headers: {}

          - name: bitget
            api_url: "https://api.bitget.com/api/spot/v1/market/ticker?symbol=BTCUSDC_SPBL"
            json_path: ["data", "close"]
            headers: {}

          - name: kucoin
            api_url: "https://api.kucoin.com/api/v1/market/orderbook/level1?symbol=BTC-USDC"
            json_path: ["data", "price"]
            headers: {}

          - name: okx
            api_url: "https://www.okx.com/api/v5/market/ticker?instId=BTC-USDC"
            json_path: ["data", 0, "last"]
            headers: {}

  quote_currency:
    api_sources:
      - adapter: generic-api
        asset_a: USDT
        asset_b: ADA
        sources:
          - name: xt
            api_url: "https://sapi.xt.com/v4/public/ticker?symbol=ada_usdt"
            json_path: ["result", 0, "c"]
            headers: {}
            inverse: true

          - name: gate
            api_url: "https://api.gateio.ws/api2/1/ticker/ada_usdt"
            json_path: ["last"]
            headers: {}
            inverse: true

          - name: crypto
            api_url: "https://api.crypto.com/v2/public/get-ticker?instrument_name=ADA_USDT"
            json_path: ["result", "data", 0, "a"]
            headers: {}
            inverse: true

          - name: huobi
            api_url: "https://api.huobi.pro/market/trade?symbol=adausdt"
            json_path: ["tick", "data", 0, "price"]
            headers: {}
            inverse: true
                       
      - adapter: generic-api
        asset_a: USD
        asset_b: ADA
        sources:
          - name: coinbase
            api_url: "https://api.exchange.coinbase.com/products/ADA-USD/ticker/"
            json_path: ["price"]
            headers: {}
            inverse: true

          - name: kraken
            api_url: "https://api.kraken.com/0/public/Ticker?pair=ADAUSD"
            json_path: ["result", "ADAUSD", "o"]
            headers: {}
            inverse: true

          - name: btse
            api_url: "https://api.btse.com/spot/api/v3.2/price?symbol=ADA-USD"
            json_path: [0, "lastPrice"]
            headers: {}
            inverse: true

          - name: bitfinex
            api_url: "https://api.bitfinex.com/v2/ticker/tADAUSD"
            json_path: [6]
            headers: {}
            inverse: true

      - adapter: generic-api
        asset_a: USDC
        asset_b: ADA
        sources:
          - name: bitget
            api_url: "https://api.bitget.com/api/spot/v1/market/ticker?symbol=ADAUSDC_SPBL"
            json_path: ["data", "close"]
            headers: {}
            inverse: true

          - name: kucoin
            api_url: "https://api.kucoin.com/api/v1/market/orderbook/level1?symbol=ADA-USDC"
            json_path: ["data", "price"]
            headers: {}
            inverse: true

          - name: okx
            api_url: "https://www.okx.com/api/v5/market/ticker?instId=ADA-USDC"
            json_path: ["data", 0, "last"]
            headers: {}
            inverse: true