include: dynamic_config.yml  

Node:
  mnemonic: <%= @mnemonic_btc_ada %>
  oracle_curr: 2e3ed96d283a549580e29dd6ec23e5f4a8020a8c1d7f2b95c4b2b4dd
  oracle_address: addr1wyujem6fwxju9arc45lm98z0uwgwm0t8aerjp5mgahpgx7snfcpuu
  c3_token_hash: 8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a
  c3_token_name: CHARLI3
  reference_script_input: 0252279ec287e2f0e349bd9d7cddefd7b00569a95d2e508560608e57a430bb1b#0
  c3_oracle_nft_hash: e2ee3c439d71d22a77ccf019953459368b4d35e6184c115d67e1c735
  c3_oracle_nft_name: OracleFeed
  c3_oracle_rate_address: addr1wxhsunv3398mrx39wm843pyjd3p4npdp6wftcq9tt8jxvhqh5dja0
  node_sync_api: https://devportal-backend-phsapb3mfq-uc.a.run.app

Rate:
  general_base_symbol: BTC-USD
  general_quote_symbol: ADA-USD 
  base_currency:
    xt:
      type: generic
      symbol: BTC-USDT
      api_url: https://sapi.xt.com
      path: /v4/public/ticker?symbol=BTC_usdt
      json_path: ["result", 0, "c"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    gate:
      type: generic
      symbol: BTC-USDT
      api_url: https://api.gateio.ws
      path: /api2/1/ticker/BTC_usdt
      json_path: ["last"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    crypto:
      type: generic
      symbol: BTC-USDT
      api_url: https://api.crypto.com
      path: /v2/public/get-ticker?instrument_name=BTC_USDT
      json_path: ["result","data",0,"a"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    huobi:
      type: generic
      symbol: BTCUSDT
      api_url: https://api.huobi.pro
      path: /market/trade?symbol=btcusdt
      json_path: ["tick","data",0,"price"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    coinbase:
      type: generic
      symbol: BTC-USD
      api_url: https://api.exchange.coinbase.com
      path: /products/BTC-USD/ticker/
      json_path: ["price"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    kraken:
      type: generic
      symbol: BTCUSD
      api_url: https://api.kraken.com
      path: /0/public/Ticker?pair=BTCUSD
      json_path: ["result","XXBTZUSD","o"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    btse:
      type: generic
      symbol: BTCUSD
      api_url: https://api.btse.com
      path: /spot/api/v3.2/price?symbol=BTC-USD
      json_path: [0,"lastPrice"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    bitfinex:
      type: generic
      symbol: tBTCUSD
      api_url: https://api.bitfinex.com
      path: /v2/ticker/tBTCUSD
      json_path: [6]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    binance_busd:
      type: binance
      symbol: BTCUSDT
      quote_currency: true
      rate_calculation_method: divide
    bitrue:
      type: generic
      symbol: BTCBUSD
      api_url: https://openapi.bitrue.com
      path: /api/v1/ticker/price?symbol=btcusdt
      json_path: ["price"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    bitget:
      type: generic
      symbol: BTC-USDC
      api_url: https://api.bitget.com
      path: /api/spot/v1/market/ticker?symbol=BTCUSDC_SPBL
      json_path: ["data","close"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    kucoin:
      type: generic
      symbol: BTC-USDC
      api_url: https://api.kucoin.com
      path: /api/v1/market/orderbook/level1?symbol=BTC-USDC
      json_path: ["data","price"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide
    okx:
      type: generic
      symbol: BTC-USDC
      api_url: https://www.okx.com
      path: /api/v5/market/ticker?instId=BTC-USDC
      json_path: ["data",0,"last"]
      key: {}
      quote_currency: true
      rate_calculation_method: divide 
  
  quote_currency:
    binance_usdt:
      type: binance
      symbol: ADAUSDT
    xt:
      type: generic
      symbol: ADA-USDT
      api_url: https://sapi.xt.com
      path: /v4/public/ticker?symbol=ada_usdt
      json_path: ["result", 0, "c"]
      key: {}
    gate:
      type: generic
      symbol: ADA-USDT
      api_url: https://api.gateio.ws
      path: /api2/1/ticker/ada_usdt
      json_path: ["last"]
      key: {}
    crypto:
      type: generic
      symbol: ADA-USDT
      api_url: https://api.crypto.com
      path: /v2/public/get-ticker?instrument_name=ADA_USDT
      json_path: ["result","data",0,"a"]
      key: {}
    huobi:
      type: generic
      symbol: ADAUSDT
      api_url: https://api.huobi.pro
      path: /market/trade?symbol=adausdt
      json_path: ["tick","data",0,"price"]
      key: {}
    coinbase:
      type: generic
      symbol: ADA-USD
      api_url: https://api.exchange.coinbase.com
      path: /products/ADA-USD/ticker/
      json_path: ["price"]
      key: {}
    kraken:
      type: generic
      symbol: ADAUSD
      api_url: https://api.kraken.com
      path: /0/public/Ticker?pair=ADAUSD
      json_path: ["result","ADAUSD","o"]
      key: {}
    btse:
      type: generic
      symbol: ADAUSD
      api_url: https://api.btse.com
      path: /spot/api/v3.2/price?symbol=ADA-USD
      json_path: [0,"lastPrice"]
      key: {}
    bitfinex:
      type: generic
      symbol: ADAUSD
      api_url: https://api.bitfinex.com
      path: /v2/ticker/tADAUSD
      json_path: [6]
      key: {}
    binance_busd:
      type: binance
      symbol: ADABUSD
    bitget:
      type: generic
      symbol: ADA-USDC
      api_url: https://api.bitget.com
      path: /api/spot/v1/market/ticker?symbol=ADAUSDC_SPBL
      json_path: ["data","close"]
      key: {}
    kucoin:
      type: generic
      symbol: ADA-USDC
      api_url: https://api.kucoin.com
      path: /api/v1/market/orderbook/level1?symbol=ADA-USDC
      json_path: ["data","price"]
      key: {}
    okx:
      type: generic
      symbol: ADA-USDC
      api_url: https://www.okx.com
      path: /api/v5/market/ticker?instId=ADA-USDC
      json_path: ["data",0,"last"]
      key: {}