include: dynamic_config.yml

Node:
  mnemonic: <%= @mnemonic_charli3_ada %>
  oracle_curr: 8aa52ae233cf0fcde60d47fd5de23b08005662e75893e33d115580b2
  oracle_address: addr1wyk4ekcm9vr6vg3c03ftn0m0h6drlqes2mqf33k9294f3uqcezsdm
  c3_token_hash: 8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a
  c3_token_name: CHARLI3
  # reference_script_input: # Optional, to be provided by Charli3 team if needed
  c3_oracle_nft_hash: e2ee3c439d71d22a77ccf019953459368b4d35e6184c115d67e1c735
  c3_oracle_nft_name: OracleFeed
  c3_oracle_rate_address: addr1wxhsunv3398mrx39wm843pyjd3p4npdp6wftcq9tt8jxvhqh5dja0

Rate:
  general_base_symbol: CHARLI3-ADA
  
  base_currency:
    # DEX sources for CHARLI3/ADA direct price using Charli3 Dendrite
    dexes:
      - adapter: charli3-dendrite
        asset_a: 8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a434841524c4933
        asset_b: lovelace
        quote_required: false
        sources:
          - minswapv2
          - vyfi
          - wingriders
          - wingridersv2
          - sundaeswapv3