include: dynamic_config.yml  

Node:
  mnemonic: <%= @mnemonic_copi_usd %>
  oracle_curr: de5f7f6063cf4fb3bbe8bbf8ad7da5bbb254dd3b35cb219a62a7a079
  oracle_address: addr1wxqrs0gcxfhgvrlnczqrhnpyzhw4pvnqwc06wg39nc77qwshf0unp
  c3_token_hash: 8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a
  c3_token_name: CHARLI3
  reference_script_input: f008baa35d776d956cfb5692ef24f459ef6e2abee212e6ee54076115bb83ade4#0
  c3_oracle_nft_hash: e2ee3c439d71d22a77ccf019953459368b4d35e6184c115d67e1c735
  c3_oracle_nft_name: OracleFeed
  c3_oracle_rate_address: addr1wxhsunv3398mrx39wm843pyjd3p4npdp6wftcq9tt8jxvhqh5dja0
  node_sync_api: https://devportal-backend-phsapb3mfq-uc.a.run.app


Rate:
  general_base_symbol: COPI-USD
  general_quote_symbol: ADA-USD 
  base_currency:
    xt:
      type: generic
      symbol: COPI-USDT
      api_url: https://sapi.xt.com
      path: /v4/public/ticker?symbol=COPI_usdt
      json_path: ["result", 0, "c"]
      key: {}
    gate:
      type: generic
      symbol: COPI-USDT
      api_url: https://api.gateio.ws
      path: /api2/1/ticker/copi_usdt
      json_path: ["last"]
      key: {}
    bitrue:
      type: generic
      symbol: COPI-USDT
      api_url: https://openapi.bitrue.com
      path: /api/v1/ticker/price?symbol=copiusdt
      json_path: ["price"]
      key: {}
    mexc:
      type: generic
      symbol: COPI-USDT
      api_url: https://www.mexc.com
      path: /open/api/v2/market/ticker?symbol=COPI_USDT
      json_path: ["data",0,"last"]
      key: {}
    minswap:
      type: minswap
      token_a_name: ADA
      token_a_decimal: 6
      token_b_name: Cornucopias [via ChainPort.io]
      token_b_decimal: 6
      pool_id: 7925263b1aff069a191db67d5ac185c029f7f43e084a4ef6e5fa2848a56e2aa6
      get_second_pool_price: false
      quote_currency: true
      rate_calculation_method: multiply
    wingriders:
      type: wingriders
      symbol: COPI
      currency_symbol: b6a7467ea1deb012808ef4e87b5ff371e85f7142d7b356a40d9b42a0
      token_name: 436f726e75636f70696173205b76696120436861696e506f72742e696f5d
      quote_currency: true
      rate_calculation_method: multiply
    vyfi:
      type: vyfi
      pool_tokens: ADA-Cornucopias [via ChainPort.io]
      pool_address: addr1zyzryy5c7l0cyrt0w4g0tua9uk4zlsds5ertx50kvvpcdpx08470jem2z3k5yap4fddtxvykxxv2tmr83x06vklv5vys3rxv2e
      minting_a_token_policy: null
      minting_b_token_policy: b6a7467ea1deb012808ef4e87b5ff371e85f7142d7b356a40d9b42a0
      get_second_pool_price: false
      quote_currency: true
      rate_calculation_method: multiply

  quote_currency:
    binance_usdt:
      type: binance
      symbol: ADAUSDT
    xt:
      type: generic
      symbol: ADA-USDT
      api_url: https://sapi.xt.com
      path: /v4/public/ticker?symbol=ada_usdt
      json_path: ["result", 0, "c"]
      key: {}
    gate:
      type: generic
      symbol: ADA-USDT
      api_url: https://api.gateio.ws
      path: /api2/1/ticker/ada_usdt
      json_path: ["last"]
      key: {}
    crypto:
      type: generic
      symbol: ADA-USDT
      api_url: https://api.crypto.com
      path: /v2/public/get-ticker?instrument_name=ADA_USDT
      json_path: ["result","data",0,"a"]
      key: {}
    huobi:
      type: generic
      symbol: ADAUSDT
      api_url: https://api.huobi.pro
      path: /market/trade?symbol=adausdt
      json_path: ["tick","data",0,"price"]
      key: {}
    coinbase:
      type: generic
      symbol: ADA-USD
      api_url: https://api.exchange.coinbase.com
      path: /products/ADA-USD/ticker/
      json_path: ["price"]
      key: {}
    kraken:
      type: generic
      symbol: ADAUSD
      api_url: https://api.kraken.com
      path: /0/public/Ticker?pair=ADAUSD
      json_path: ["result","ADAUSD","o"]
      key: {}
    btse:
      type: generic
      symbol: ADAUSD
      api_url: https://api.btse.com
      path: /spot/api/v3.2/price?symbol=ADA-USD
      json_path: [0,"lastPrice"]
      key: {}
    bitfinex:
      type: generic
      symbol: ADAUSD
      api_url: https://api.bitfinex.com
      path: /v2/ticker/tADAUSD
      json_path: [6]
      key: {}
    binance_busd:
      type: binance
      symbol: ADABUSD
    bitget:
      type: generic
      symbol: ADA-USDC
      api_url: https://api.bitget.com
      path: /api/spot/v1/market/ticker?symbol=ADAUSDC_SPBL
      json_path: ["data","close"]
      key: {}
    kucoin:
      type: generic
      symbol: ADA-USDC
      api_url: https://api.kucoin.com
      path: /api/v1/market/orderbook/level1?symbol=ADA-USDC
      json_path: ["data","price"]
      key: {}
    okx:
      type: generic
      symbol: ADA-USDC
      api_url: https://www.okx.com
      path: /api/v5/market/ticker?instId=ADA-USDC
      json_path: ["data",0,"last"]
      key: {}