Updater:
  update_inter: 120
  verbosity: INFO
  percent_resolution: 10000  

Node:
  mnemonic: # <--- Insert your mnemonic here
  oracle_curr: a665bb42594646eaaed8ed59ada592fb8300775df916a4a5406ffa96
  oracle_addr: addr1w9w2ka2cue4ytyhsr8j8g3l7a9z9jvzgvpm4wj476dpfldq2shdcx
  c3_token_hash: 8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a
  c3_token_name: CHARLI3
  # reference_script_input: fd2f28101a70dad92bc97e7d3b05da6e8d476507b931c0e40466684b42d6c625#0
  c3_oracle_nft_hash: e2ee3c439d71d22a77ccf019953459368b4d35e6184c115d67e1c735
  c3_oracle_nft_name: OracleFeed
  c3_oracle_rate_address: addr1wxhsunv3398mrx39wm843pyjd3p4npdp6wftcq9tt8jxvhqh5dja0

ChainQuery:
  network: MAINNET
  ogmios:
    ws_url: # <--- Insert your ogmios ws url here
    kupo_url: # <--- Insert your kupo url here

Rate:
  base_currency:
    vyfi:
      type: vyfi
      pool_tokens: ADA-DjedMicroUSD
      pool_address: addr1zxv6j97nwullvdw6e67xjzpgf6jqyetva2eh86e6tgq8map8kq9dr3l47k6mfgvuugac48lc7p9zq25t6r4323hjux9qkfmqw5
      minting_a_token_policy: null
      minting_b_token_policy: 8db269c3ec630e06ae29f74bc39edd1f87c819f1056206e879a1cd61
      get_second_pool_price: false
      quote_currency: true
      rate_calculation_method: multiply
    wingriders:
      type: wingriders
      symbol: DJED
      currency_symbol: 8db269c3ec630e06ae29f74bc39edd1f87c819f1056206e879a1cd61
      token_name: 446a65644d6963726f555344
      quote_currency: true
      rate_calculation_method: multiply
    sundaeswap:
      type: sundaeswap
      symbol: DJED
      pool_ident: f803
      quote_currency: true
      rate_calculation_method: multiply
    minswap:
      type: minswap
      token_a_name: ADA
      token_a_decimal: 6
      token_b_name: DjedMicroUSD
      token_b_decimal: 6
      pool_id: d944eda9d4fd8c26171a4362539bfd4ccf35f5a4d0cc7525b22327b997a4f4b9
      get_second_pool_price: false
      quote_currency: true
      rate_calculation_method: multiply
    coingecko:
      type: generic
      symbol: DJED-USD
      api_url: https://pro-api.coingecko.com
      path: /api/v3/simple/price?ids=djed&vs_currencies=usd
      json_path: ["djed","usd"]
      key: 
        x-cg-pro-api-key: CG-N8W262z5GCZSFs1fREq3Gi1A
    coinmarketcap:
      type: generic
      symbol: DJED-USD
      api_url: https://pro-api.coinmarketcap.com
      path: /v2/cryptocurrency/quotes/latest?symbol=djed
      json_path: ["data","DJED",0,"quote","USD","price"]
      key: {
        "X-CMC_PRO_API_KEY": "cc8dd3a2-67f9-4bc6-8378-c0f9823109e0"
      }
  quote_currency:
    binance_usdt:
      type: binance
      symbol: ADAUSDT
    xt:
      type: generic
      symbol: ADA-USDT
      api_url: https://sapi.xt.com
      path: /v4/public/ticker?symbol=ada_usdt
      json_path: ["result", 0, "c"]
      key: {}
    gate:
      type: generic
      symbol: ADA-USDT
      api_url: https://api.gateio.ws
      path: /api2/1/ticker/ada_usdt
      json_path: ["last"]
      key: {}
    crypto:
      type: generic
      symbol: ADA-USDT
      api_url: https://api.crypto.com
      path: /v2/public/get-ticker?instrument_name=ADA_USDT
      json_path: ["result","data",0,"a"]
      key: {}
    huobi:
      type: generic
      symbol: ADAUSDT
      api_url: https://api.huobi.pro
      path: /market/trade?symbol=adausdt
      json_path: ["tick","data",0,"price"]
      key: {}
    coinbase:
      type: generic
      symbol: ADA-USD
      api_url: https://api.exchange.coinbase.com
      path: /products/ADA-USD/ticker/
      json_path: ["price"]
      key: {}
    kraken:
      type: generic
      symbol: ADAUSD
      api_url: https://api.kraken.com
      path: /0/public/Ticker?pair=ADAUSD
      json_path: ["result","ADAUSD","o"]
      key: {}
    btse:
      type: generic
      symbol: ADAUSD
      api_url: https://api.btse.com
      path: /spot/api/v3.2/price?symbol=ADA-USD
      json_path: [0,"lastPrice"]
      key: {}
    bitfinex:
      type: generic
      symbol: ADAUSD
      api_url: https://api.bitfinex.com
      path: /v2/ticker/tADAUSD
      json_path: [6]
      key: {}
    binance_busd:
      type: binance
      symbol: ADABUSD
    bitget:
      type: generic
      symbol: ADA-USDC
      api_url: https://api.bitget.com
      path: /api/spot/v1/market/ticker?symbol=ADAUSDC_SPBL
      json_path: ["data","close"]
      key: {}
    kucoin:
      type: generic
      symbol: ADA-USDC
      api_url: https://api.kucoin.com
      path: /api/v1/market/orderbook/level1?symbol=ADA-USDC
      json_path: ["data","price"]
      key: {}
    okx:
      type: generic
      symbol: ADA-USDC
      api_url: https://www.okx.com
      path: /api/v5/market/ticker?instId=ADA-USDC
      json_path: ["data",0,"last"]
      key: {}