version: "3.5"

services:  
  charli3-node-operator-db:
    image: postgres:16
    environment:
      POSTGRES_USER: charli3
      POSTGRES_PASSWORD: charli3
      POSTGRES_DB: node-operator-backend
    volumes:
      - charli3-node-operator-db:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d node-operator-backend -U charli3"]
      interval: 10s
      timeout: 5s
      retries: 5

  charli3-migrations:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.9.1
    volumes:
      - "./dynamic_config.yml:/app/config.yml"
    command: ["python3", "migrations.py"]
    depends_on:
      charli3-node-operator-db:
        condition: service_healthy

  charli3-ada-charli3-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.9.1
    volumes:
      - "./ada_charli3_v3_config.yml:/app/config.yml"
      - "./dynamic_config.yml:/app/dynamic_config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    depends_on:
      charli3-migrations:
        condition: service_completed_successfully

  charli3-ada-usd-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.9.1
    volumes:
      - "./ada_usd_v3_config.yml:/app/config.yml"
      - "./dynamic_config.yml:/app/dynamic_config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    depends_on:
      charli3-migrations:
        condition: service_completed_successfully

  charli3-book-usd-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.9.1
    volumes:
      - "./book_usd_v3_config.yml:/app/config.yml"
      - "./dynamic_config.yml:/app/dynamic_config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    depends_on:
      charli3-migrations:
        condition: service_completed_successfully

  charli3-nmkr-ada-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.9.1
    volumes:
      - "./nmkr_ada_v3_config.yml:/app/config.yml"
      - "./dynamic_config.yml:/app/dynamic_config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    depends_on:
      charli3-migrations:
        condition: service_completed_successfully

  charli3-ada-euro-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.9.1
    volumes:
      - "./ada_euro_v3_config.yml:/app/config.yml"
      - "./dynamic_config.yml:/app/dynamic_config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    depends_on:
      charli3-migrations:
        condition: service_completed_successfully

  charli3-ada-chf-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.9.1
    volumes:
      - "./ada_chf_v3_config.yml:/app/config.yml"
      - "./dynamic_config.yml:/app/dynamic_config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    depends_on:
      charli3-migrations:
        condition: service_completed_successfully

  charli3-mehen-usd-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.9.1
    volumes:
      - "./mehen_usd_v3_config.yml:/app/config.yml"
      - "./dynamic_config.yml:/app/dynamic_config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    depends_on:
      charli3-migrations:
        condition: service_completed_successfully

  charli3-newm-usd-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.9.1
    volumes:
      - "./newm_usd_v3_config.yml:/app/config.yml"
      - "./dynamic_config.yml:/app/dynamic_config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    depends_on:
      charli3-migrations:
        condition: service_completed_successfully

  charli3-copi-usd-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.9.1
    volumes:
      - "./copi_usd_v3_config.yml:/app/config.yml"
      - "./dynamic_config.yml:/app/dynamic_config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    depends_on:
      charli3-migrations:
        condition: service_completed_successfully

  charli3-btc-ada-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.9.1
    volumes:
      - "./btc_ada_v3_config.yml:/app/config.yml"
      - "./dynamic_config.yml:/app/dynamic_config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    depends_on:
      charli3-migrations:
        condition: service_completed_successfully

  charli3-wmt-usd-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.9.1
    volumes:
      - "./wmt_usd_v3_config.yml:/app/config.yml"
      - "./dynamic_config.yml:/app/dynamic_config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    depends_on:
      charli3-migrations:
        condition: service_completed_successfully

  charli3-snek-usd-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.9.1
    volumes:
      - "./snek_usd_v3_config.yml:/app/config.yml"
      - "./dynamic_config.yml:/app/dynamic_config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
    depends_on:
      charli3-migrations:
        condition: service_completed_successfully


volumes:
  charli3-node-operator-db:
