version: "3.5"

services:  
  charli3-node-operator-db:
    image: postgres:16
    environment:
      POSTGRES_USER: charli3
      POSTGRES_PASSWORD: charli3
      POSTGRES_DB: node-operator-backend
    volumes:
      - charli3-node-operator-db:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  charli3-ada-charli3-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.0.4
    volumes:
      - "./ada_charli3_v3_config.yml:/app/config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  charli3-ada-usd-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.0.4
    volumes:
      - "./ada_usd_v3_config.yml:/app/config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  charli3-book-usd-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.0.4
    volumes:
      - "./book_usd_v3_config.yml:/app/config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  charli3-djed-usd-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.0.4
    volumes:
      - "./djed_usd_v3_config.yml:/app/config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  charli3-iusd-usd-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.0.4
    volumes:
      - "./iusd_usd_v3_config.yml:/app/config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"  

  charli3-nmkr-ada-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.0.4
    volumes:
      - "./nmkr_ada_v3_config.yml:/app/config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  charli3-ada-euro-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.0.4
    volumes:
      - "./ada_euro_v3_config.yml:/app/config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  charli3-ada-chf-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.0.4
    volumes:
      - "./ada_chf_v3_config.yml:/app/config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  charli3-shen-usd-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.0.4
    volumes:
      - "./shen_usd_v3_config.yml:/app/config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  charli3-mehen-usd-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.0.4
    volumes:
      - "./mehen_usd_v3_config.yml:/app/config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  charli3-newm-usd-v3:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v2.0.4
    volumes:
      - "./newm_usd_v3_config.yml:/app/config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"


volumes:
  charli3-node-operator-db: