version: "3.5"

services:
  charli3-node-backend:
    image: us-central1-docker.pkg.dev/charli3-mainnet/node-operator-backend/node-operator-backend:v1.5.0
    volumes:
      - "./config.yml:/app/config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
