version: "3.5"

services:
  charli3-backend:
    image: 372773567348.dkr.ecr.us-west-1.amazonaws.com/charli3-backend-v2:pycardano-poetry
    volumes:
      - "./config.yml:/app/config.yml"
    restart: always
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
