Updater:
  update_inter: 150
  verbosity: INFO
  percent_resolution: 10000  

database:
  url: "postgresql+asyncpg://charli3:charli3@charli3-node-operator-db:5432/node-operator-backend"

Node:
  mnemonic: # <--- Insert your mnemonic here  
  oracle_curr: f155a26044efe91b3c44f87a7536d2d631c847717930ff547ae9d05c
  oracle_address: addr1wy32q7067yt9c2em8kx5us4vhxzv4xve24u6j8ptlc5mzqcahrwzt
  c3_token_hash: 8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a
  c3_token_name: CHARLI3
  c3_oracle_nft_hash: e2ee3c439d71d22a77ccf019953459368b4d35e6184c115d67e1c735
  c3_oracle_nft_name: OracleFeed
  c3_oracle_rate_address: addr1wxhsunv3398mrx39wm843pyjd3p4npdp6wftcq9tt8jxvhqh5dja0
  node_sync_api: https://devportal-backend-phsapb3mfq-uc.a.run.app

ChainQuery:
  network: MAINNET
  ogmios:
    ws_url: # <--- Insert your ogmios ws url here
    kupo_url: # <--- Insert your kupo url here

Rate:
  base_currency:
    muesliswap:
      type: muesliswap
      symbol: NEWM/ADA
      currency_symbol: 682fe60c9918842b3323c43b5144bc3d52a23bd2fb81345560d73f63
      token_name: 4e45574d
      quote_currency: true
      rate_calculation_method: multiply
    wingriders:
      type: wingriders
      symbol: NEWM
      currency_symbol: 682fe60c9918842b3323c43b5144bc3d52a23bd2fb81345560d73f63
      token_name: 4e45574d
      quote_currency: true
      rate_calculation_method: multiply
    vyfi:
      type: vyfi
      pool_tokens: ADA-NEWM
      pool_address: addr1zxwgyyawp226e6jxkqcjpzws0qyac0eu3teqd99088cjhu760wckas4haxwwclas0g39cc8cvt2r8yalrfa9e8vxx92q6qsmnq
      minting_a_token_policy: null
      minting_b_token_policy: 682fe60c9918842b3323c43b5144bc3d52a23bd2fb81345560d73f63
      get_second_pool_price: false
      quote_currency: true
      rate_calculation_method: multiply
    minswap:
      type: minswap
      token_a_name: ADA
      token_a_decimal: 6
      token_b_name: NEWM
      token_b_decimal: 6
      pool_id: 9f692349af450e68e02abb291e3bcabe42251029498dd0482d8b6b0a740a40d8
      get_second_pool_price: false
      quote_currency: true
      rate_calculation_method: multiply
    sundaeswap:
      type: sundaeswap
      symbol: NEWM
      pool_ident: "85"
      quote_currency: true
      rate_calculation_method: multiply
  quote_currency:
    binance_usdt:
      type: binance
      symbol: ADAUSDT
    xt:
      type: generic
      symbol: ADA-USDT
      api_url: https://sapi.xt.com
      path: /v4/public/ticker?symbol=ada_usdt
      json_path: ["result", 0, "c"]
      key: {}
    gate:
      type: generic
      symbol: ADA-USDT
      api_url: https://api.gateio.ws
      path: /api2/1/ticker/ada_usdt
      json_path: ["last"]
      key: {}
    crypto:
      type: generic
      symbol: ADA-USDT
      api_url: https://api.crypto.com
      path: /v2/public/get-ticker?instrument_name=ADA_USDT
      json_path: ["result","data",0,"a"]
      key: {}
    huobi:
      type: generic
      symbol: ADAUSDT
      api_url: https://api.huobi.pro
      path: /market/trade?symbol=adausdt
      json_path: ["tick","data",0,"price"]
      key: {}
    coinbase:
      type: generic
      symbol: ADA-USD
      api_url: https://api.exchange.coinbase.com
      path: /products/ADA-USD/ticker/
      json_path: ["price"]
      key: {}
    kraken:
      type: generic
      symbol: ADAUSD
      api_url: https://api.kraken.com
      path: /0/public/Ticker?pair=ADAUSD
      json_path: ["result","ADAUSD","o"]
      key: {}
    btse:
      type: generic
      symbol: ADAUSD
      api_url: https://api.btse.com
      path: /spot/api/v3.2/price?symbol=ADA-USD
      json_path: [0,"lastPrice"]
      key: {}
    bitfinex:
      type: generic
      symbol: ADAUSD
      api_url: https://api.bitfinex.com
      path: /v2/ticker/tADAUSD
      json_path: [6]
      key: {}
    binance_busd:
      type: binance
      symbol: ADABUSD
    bitget:
      type: generic
      symbol: ADA-USDC
      api_url: https://api.bitget.com
      path: /api/spot/v1/market/ticker?symbol=ADAUSDC_SPBL
      json_path: ["data","close"]
      key: {}
    kucoin:
      type: generic
      symbol: ADA-USDC
      api_url: https://api.kucoin.com
      path: /api/v1/market/orderbook/level1?symbol=ADA-USDC
      json_path: ["data","price"]
      key: {}
    okx:
      type: generic
      symbol: ADA-USDC
      api_url: https://www.okx.com
      path: /api/v5/market/ticker?instId=ADA-USDC
      json_path: ["data",0,"last"]
      key: {}