include: dynamic_config.yml   

Node:
  mnemonic: <%= @mnemonic_nmkr_ada %>
  oracle_curr: 6167e3550a74ead031eaebe9ebddbf4d8fb9d9398568261d41bc9e97
  oracle_address: addr1w9cjzxxgpyqfkd9hgl2rc7qmz963nq4ml2l63t9zzpmj9vsf3pldw
  c3_token_hash: 8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a
  c3_token_name: CHARLI3
  # reference_script_input: 6526673e89d0f2daa260e2e71e0f46cd8a2245ec3a41352019ea957dd0dc2a85#0
  c3_oracle_nft_hash: e2ee3c439d71d22a77ccf019953459368b4d35e6184c115d67e1c735
  c3_oracle_nft_name: OracleFeed
  c3_oracle_rate_address: addr1wxhsunv3398mrx39wm843pyjd3p4npdp6wftcq9tt8jxvhqh5dja0
  node_sync_api: https://devportal-backend-phsapb3mfq-uc.a.run.app


Rate:
  general_base_symbol: NMKR-ADA
  
  base_currency:
    dexes:
      - adapter: charli3-dendrite
        asset_a: 5dac8536653edc12f6f5e1045d8164b9f59998d3bdc300fc928434894e4d4b52
        asset_b: lovelace
        quote_required: false
        sources:
          - minswapv2
          - vyfi
          - wingriders
          - spectrum
          - sundaeswap
          - sundaeswapv3
          - muesliswap