include: dynamic_config.yml   

Node:
  mnemonic: <%= @mnemonic_snek_usd %>
  oracle_curr: 05c4aacc0d57578d5ae985f08f36b83db7026b0bb5890571619628bd
  oracle_address: addr1wxh4ccz9g0fxgx3ejwjexxstyrkceerz23xd6gmly7gr9ygpdv5ns
  c3_token_hash: 8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a
  c3_token_name: CHARLI3
  # reference_script_input: #0
  c3_oracle_nft_hash: e2ee3c439d71d22a77ccf019953459368b4d35e6184c115d67e1c735
  c3_oracle_nft_name: OracleFeed
  c3_oracle_rate_address: addr1wxhsunv3398mrx39wm843pyjd3p4npdp6wftcq9tt8jxvhqh5dja0

Rate:
  general_base_symbol: SNEK-ADA
  general_quote_symbol: ADA-USD

  base_currency:
    dexes:
      - adapter: charli3-dendrite
        asset_a: 279c909f348e533da5808898f87f9a14bb2c3dfbbacccd631d927a3f534e454b
        asset_b: lovelace
        quote_required: true
        quote_calc_method: multiply
        sources:
          - minswapv2
          - sundaeswap
          - sundaeswapv3
          - muesliswap
        
    api_sources:
      - adapter: generic-api
        asset_a: SNEK
        asset_b: USD
        quote_required: false
        sources:
          - name: gate
            api_url: "https://api.gateio.ws/api2/1/ticker/snek_usdt"
            json_path: ["last"]
            headers: {}

          - name: mexc
            api_url: "https://api.mexc.com/api/v3/ticker/price?symbol=SNEKUSDT"
            json_path: ["price"]
            headers: {}

          - name: bitget
            api_url: "https://api.bitget.com/api/v2/spot/market/tickers?symbol=SNEKUSDT"
            json_path: ["data", 0, "lastPr"]
            headers: {}

          - name: bitrue
            api_url: "https://openapi.bitrue.com/api/v1/ticker/price?symbol=snekusdt"
            json_path: ["price"]
            headers: {}

          - name: bitmart
            api_url: "https://api-cloud.bitmart.com/spot/quotation/v3/ticker?symbol=SNEK_USDT"
            json_path: ["data", "last"]
            headers: {}

          - name: coinex
            api_url: "https://api.coinex.com/v2/spot/ticker?market=SNEKUSDT"
            json_path: ["data", 0, "last"]
            headers: {}

  quote_currency:
    api_sources:
      - adapter: generic-api
        asset_a: ADA
        asset_b: USDT
        sources:
          - name: xt
            api_url: "https://sapi.xt.com/v4/public/ticker?symbol=ada_usdt"
            json_path: ["result", 0, "c"]
            headers: {}

          - name: gate
            api_url: "https://api.gateio.ws/api2/1/ticker/ada_usdt"
            json_path: ["last"]
            headers: {}

          - name: crypto
            api_url: "https://api.crypto.com/v2/public/get-ticker?instrument_name=ADA_USDT"
            json_path: ["result", "data", 0, "a"]
            headers: {}

          - name: huobi
            api_url: "https://api.huobi.pro/market/trade?symbol=adausdt"
            json_path: ["tick", "data", 0, "price"]
            headers: {}
                       
      - adapter: generic-api
        asset_a: ADA
        asset_b: USD
        sources:
          - name: coinbase
            api_url: "https://api.exchange.coinbase.com/products/ADA-USD/ticker/"
            json_path: ["price"]
            headers: {}

          - name: kraken
            api_url: "https://api.kraken.com/0/public/Ticker?pair=ADAUSD"
            json_path: ["result", "ADAUSD", "o"]
            headers: {}

          - name: btse
            api_url: "https://api.btse.com/spot/api/v3.2/price?symbol=ADA-USD"
            json_path: [0, "lastPrice"]
            headers: {}

          - name: bitfinex
            api_url: "https://api.bitfinex.com/v2/ticker/tADAUSD"
            json_path: [6]
            headers: {}

      - adapter: generic-api
        asset_a: ADA
        asset_b: USDC
        sources:
          - name: bitget
            api_url: "https://api.bitget.com/api/spot/v1/market/ticker?symbol=ADAUSDC_SPBL"
            json_path: ["data", "close"]
            headers: {}

          - name: kucoin
            api_url: "https://api.kucoin.com/api/v1/market/orderbook/level1?symbol=ADA-USDC"
            json_path: ["data", "price"]
            headers: {}

          - name: okx
            api_url: "https://www.okx.com/api/v5/market/ticker?instId=ADA-USDC"
            json_path: ["data", 0, "last"]
            headers: {}