include: dynamic_config.yml   

Node:
  mnemonic: <%= @mnemonic_snek_usd %>
  oracle_curr: 05c4aacc0d57578d5ae985f08f36b83db7026b0bb5890571619628bd
  oracle_address: addr1wxh4ccz9g0fxgx3ejwjexxstyrkceerz23xd6gmly7gr9ygpdv5ns
  c3_token_hash: 8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a
  c3_token_name: CHARLI3
  # reference_script_input: #0
  c3_oracle_nft_hash: e2ee3c439d71d22a77ccf019953459368b4d35e6184c115d67e1c735
  c3_oracle_nft_name: OracleFeed
  c3_oracle_rate_address: addr1wxhsunv3398mrx39wm843pyjd3p4npdp6wftcq9tt8jxvhqh5dja0
  node_sync_api: https://devportal-backend-phsapb3mfq-uc.a.run.app

Rate:
  general_base_symbol: SNEK-USD
  general_quote_symbol: ADA-USD 
  base_currency:
    gate:
      type: generic
      symbol: SNEK-USDT
      api_url: https://api.gateio.ws
      path: /api2/1/ticker/snek_usdt
      json_path: ["last"]
      key: {}
    mexc:
      type: generic
      symbol: SNEK-USDT
      api_url: https://www.mexc.com
      path: /open/api/v2/market/ticker?symbol=SNEK_USDT
      json_path: ["data",0,"last"]
      key: {}
    bitget:
      type: generic
      symbol: SNEK-USDT
      api_url: https://api.bitget.com
      path: /api/v2/spot/market/tickers?symbol=SNEKUSDT
      json_path: ["data",0,"lastPr"]
    bitrue:
      type: generic
      symbol: SNEK-USDT
      api_url: https://openapi.bitrue.com
      path: /api/v1/ticker/price?symbol=snekusdt
      json_path: ["price"]
      key: {}
    bitmart:
      type: generic
      symbol: SNEK-USDT
      api_url: https://api-cloud.bitmart.com
      path: /spot/quotation/v3/ticker?symbol=SNEK_USDT
      json_path: ["data","last"]
      key: {}
    coinex:
      type: generic
      symbol: SNEK-USD
      api_url: https://api.coinex.com
      path: /v2/spot/ticker?market=SNEKUSDT
      json_path: ["data",0,"last"]
      key: {}
    minswap:
      type: minswap
      token_a_name: ADA
      token_a_decimal: 6
      token_b_name: SNEK
      token_b_decimal: 6
      pool_id: 63f2cbfa5bf8b68828839a2575c8c70f14a32f50ebbfa7c654043269793be896
      get_second_pool_price: false
      quote_currency: true
      rate_calculation_method: multiply
  quote_currency:
    binance_usdt:
      type: binance
      symbol: ADAUSDT
    xt:
      type: generic
      symbol: ADA-USDT
      api_url: https://sapi.xt.com
      path: /v4/public/ticker?symbol=ada_usdt
      json_path: ["result", 0, "c"]
      key: {}
    gate:
      type: generic
      symbol: ADA-USDT
      api_url: https://api.gateio.ws
      path: /api2/1/ticker/ada_usdt
      json_path: ["last"]
      key: {}
    crypto:
      type: generic
      symbol: ADA-USDT
      api_url: https://api.crypto.com
      path: /v2/public/get-ticker?instrument_name=ADA_USDT
      json_path: ["result","data",0,"a"]
      key: {}
    huobi:
      type: generic
      symbol: ADAUSDT
      api_url: https://api.huobi.pro
      path: /market/trade?symbol=adausdt
      json_path: ["tick","data",0,"price"]
      key: {}
    coinbase:
      type: generic
      symbol: ADA-USD
      api_url: https://api.exchange.coinbase.com
      path: /products/ADA-USD/ticker/
      json_path: ["price"]
      key: {}
    kraken:
      type: generic
      symbol: ADAUSD
      api_url: https://api.kraken.com
      path: /0/public/Ticker?pair=ADAUSD
      json_path: ["result","ADAUSD","o"]
      key: {}
    btse:
      type: generic
      symbol: ADAUSD
      api_url: https://api.btse.com
      path: /spot/api/v3.2/price?symbol=ADA-USD
      json_path: [0,"lastPrice"]
      key: {}
    bitfinex:
      type: generic
      symbol: ADAUSD
      api_url: https://api.bitfinex.com
      path: /v2/ticker/tADAUSD
      json_path: [6]
      key: {}
    binance_busd:
      type: binance
      symbol: ADABUSD
    bitget:
      type: generic
      symbol: ADA-USDC
      api_url: https://api.bitget.com
      path: /api/spot/v1/market/ticker?symbol=ADAUSDC_SPBL
      json_path: ["data","close"]
      key: {}
    kucoin:
      type: generic
      symbol: ADA-USDC
      api_url: https://api.kucoin.com
      path: /api/v1/market/orderbook/level1?symbol=ADA-USDC
      json_path: ["data","price"]
      key: {}
    okx:
      type: generic
      symbol: ADA-USDC
      api_url: https://www.okx.com
      path: /api/v5/market/ticker?instId=ADA-USDC
      json_path: ["data",0,"last"]
      key: {}