include: dynamic_config.yml

Node:
  mnemonic: <%= @mnemonic_newm_usd %>
  oracle_curr: 9792697c10d71f6455e3b75e6cf1ae0ce730dbf81d52f0184159ac41
  oracle_address: addr1wyxq728k9pka686lzfkdyv60marz94swec9ef9mkxfqhyfqezqyjz
  c3_token_hash: 8e51398904a5d3fc129fbf4f1589701de23c7824d5c90fdb9490e15a
  c3_token_name: CHARLI3
  c3_oracle_nft_hash: e2ee3c439d71d22a77ccf019953459368b4d35e6184c115d67e1c735
  c3_oracle_nft_name: OracleFeed
  c3_oracle_rate_address: addr1wxhsunv3398mrx39wm843pyjd3p4npdp6wftcq9tt8jxvhqh5dja0
  node_sync_api: https://devportal-backend-phsapb3mfq-uc.a.run.app

Rate:
  # Ensure the symbols are used correctly (e.g., ADA-SHEN instead of SHEN-ADA)
  general_base_symbol: USDM-ADA
  general_quote_symbol: ADA-USD
  base_currency:
    muesliswap:
      type: muesliswap
      symbol: USDM/ADA
      currency_symbol: c48cbb3d5e57ed56e276bc45f99ab39abe94e6cd7ac39fb402da47ad
      token_name: "0014df105553444d"
      quote_currency: true
      rate_calculation_method: multiply
    # vyfi:
    #   type: vyfi
    #   pool_tokens: ADA-0014df105553444d
    #   pool_address: addr1z8m3eddhuq33pnnp3ystxv0dhq7fshcnht2a35594rc8ppdksyd8pn7amnr48geat0yft0uezfunealzy4ghl0cayp4sgsrtsk
    #   minting_a_token_policy:
    #   minting_b_token_policy: c48cbb3d5e57ed56e276bc45f99ab39abe94e6cd7ac39fb402da47ad
    #   get_second_pool_price: false
    #   quote_currency: true
    #   rate_calculation_method: multiply
    # minswap:
    #   type: minswap
    #   token_a_name: ADA
    #   token_a_decimal: 6
    #   token_b_name: 0014df105553444d
    #   token_b_decimal: 6
    #   pool_id: 116df62938bc100b55c0e72b57a48dced2f928635ad66660bc165a8f40f8e735
    #   get_second_pool_price: false
    #   quote_currency: true
    #   rate_calculation_method: multiply
    wingriders:
      type: wingriders
      symbol: USDM
      currency_symbol: c48cbb3d5e57ed56e276bc45f99ab39abe94e6cd7ac39fb402da47ad
      token_name: "0014df105553444d"
      quote_currency: true
      rate_calculation_method: multiply
    sundaeswap:
      type: sundaeswap
      symbol: usdm
      pool_ident: 6105
      quote_currency: true
      rate_calculation_method: multiply
  quote_currency:
    binance_usdt:
      type: binance
      symbol: ADAUSDT
    xt:
      type: generic
      symbol: ADA-USDT
      api_url: https://sapi.xt.com
      path: /v4/public/ticker?symbol=ada_usdt
      json_path: ["result", 0, "c"]
      key: {}
    gate:
      type: generic
      symbol: ADA-USDT
      api_url: https://api.gateio.ws
      path: /api2/1/ticker/ada_usdt
      json_path: ["last"]
      key: {}
    crypto:
      type: generic
      symbol: ADA-USDT
      api_url: https://api.crypto.com
      path: /v2/public/get-ticker?instrument_name=ADA_USDT
      json_path: ["result","data",0,"a"]
      key: {}
    huobi:
      type: generic
      symbol: ADAUSDT
      api_url: https://api.huobi.pro
      path: /market/trade?symbol=adausdt
      json_path: ["tick","data",0,"price"]
      key: {}
    coinbase:
      type: generic
      symbol: ADA-USD
      api_url: https://api.exchange.coinbase.com
      path: /products/ADA-USD/ticker/
      json_path: ["price"]
      key: {}
    kraken:
      type: generic
      symbol: ADAUSD
      api_url: https://api.kraken.com
      path: /0/public/Ticker?pair=ADAUSD
      json_path: ["result","ADAUSD","o"]
      key: {}
    btse:
      type: generic
      symbol: ADAUSD
      api_url: https://api.btse.com
      path: /spot/api/v3.2/price?symbol=ADA-USD
      json_path: [0,"lastPrice"]
      key: {}
    bitfinex:
      type: generic
      symbol: ADAUSD
      api_url: https://api.bitfinex.com
      path: /v2/ticker/tADAUSD
      json_path: [6]
      key: {}
    binance_busd:
      type: binance
      symbol: ADABUSD
    bitget:
      type: generic
      symbol: ADA-USDC
      api_url: https://api.bitget.com
      path: /api/spot/v1/market/ticker?symbol=ADAUSDC_SPBL
      json_path: ["data","close"]
      key: {}
    kucoin:
      type: generic
      symbol: ADA-USDC
      api_url: https://api.kucoin.com
      path: /api/v1/market/orderbook/level1?symbol=ADA-USDC
      json_path: ["data","price"]
      key: {}
    okx:
      type: generic
      symbol: ADA-USDC
      api_url: https://www.okx.com
      path: /api/v5/market/ticker?instId=ADA-USDC
      json_path: ["data",0,"last"]
